---
title: "translate_progeny_model_dorothea_regulon"
author: "Christian Holland"
date: "13/09/2018"
output: html_document
---

```{r "knitr config", cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::knit(..., quiet = TRUE)
```


### Libraries and sources
These libraries and sources are used in this analysis 
```{r "setup", message=F}
library(biomaRt)
library(tidyverse)
```

### Create annotaion file between MGI and HGNC symbols
```{r "create annotaion files"}
# host = "http://apr2019.archive.ensembl.org"
mouse_ensembl = useMart("ensembl",dataset="mmusculus_gene_ensembl")
human_ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# mgi symbol - hgnc symbol
getLDS(attributes = c("mgi_symbol"),
       mart = mouse_ensembl,
       attributesL = c("hgnc_symbol"), martL = human_ensembl) %>%
  as_tibble() %>%
  rename(mgi_symbol = MGI.symbol, hgnc_symbol = HGNC.symbol) %>%
  na_if("") %>%
  write_csv("data/annotations/annotation_mgi_hgnc.csv")
```

### Translate human PROGENy matrix to mouse
```{r "translate full progeny matrix to mouse"}
# load annotation file and remove predicted genes
annotation_mgi_hgnc = read_csv("data/annotations/annotation_mgi_hgnc.csv") %>%
  drop_na() %>%
  filter(!str_detect(mgi_symbol, "^Gm[:digit:]+"))

# load full human progeny matrix
full_human_matrix = read_csv(
  "data/progeny_benchmark/models/progeny_matrix_human_full_v1.csv"
  )

# human to mouse mapping
full_mouse_matrix = full_human_matrix %>%
  rename(hgnc_symbol = gene) %>%
  inner_join(annotation_mgi_hgnc, by="hgnc_symbol") %>%
  rename(weight = zscore) %>%
  # when multiple mgi symbols are mapped to a single hgnc symbol the progeny 
  # weight is divided by the number of mapping mgi symbols
  group_by(hgnc_symbol, pathway) %>% 
  add_count(hgnc_symbol) %>%
  ungroup() %>%
  mutate(weight = weight/n,
         p.value = p.value) %>%
  # when multiple hgnc are mapped to a single mgi symbol the progeny weight of 
  # the single mgi symbol is the mean of the corresponding hgnc symbols
  group_by(mgi_symbol, pathway) %>%
  summarise(weight = mean(weight),
            p.value = mean(p.value)) %>%
  ungroup() %>%
  rename(gene = mgi_symbol) %>%
  arrange(pathway, gene)

# select top 100 genes per pathway based on most significant p-values
tmp_mouse_progeny = full_mouse_matrix %>%
  group_by(pathway) %>%
  top_n(100, -p.value) %>%
  ungroup()


# Compensation for mapping problem. E.g. the human gene SERPINA3 is a footprint 
# gene of TNFa and maps to 10 mgi ortholog genes. Thus we bias the TNFa pathway 
# to SERPINA3. 10 % - (10 out of 100 genes) of the footprint are based on 
# SERPINA3. We correct this by adding [number of duplicates - 1] new genes to 
# the footprint

# demonstration of mapping problem 
tmp_mouse_progeny %>% 
  filter(pathway == "TNFa") %>% 
  filter(round(weight,2) == 1.14) %>%
  inner_join(rename(annotation_mgi_hgnc, gene = mgi_symbol), by="gene")

tmp_mouse_progeny %>% 
  filter(pathway == "JAK-STAT") %>% 
  filter(round(weight,2) == 1.88) %>%
  inner_join(rename(annotation_mgi_hgnc, gene = mgi_symbol), by="gene")

# how many genes need to be added to footprints due to duplicating during mapping process
number_of_additional_genes = tmp_mouse_progeny %>% 
  count(pathway, weight) %>%
  filter(n>1) %>%
  mutate(number_of_extra_genes = n - 1) %>%
  group_by(pathway) %>%
  tally(number_of_extra_genes)

# build mouse progeny compensating for duplication problem
mouse_progeny = full_mouse_matrix %>%
  # remove genes with are already available in the footprint of a pathway
  anti_join(tmp_mouse_progeny, by=c("pathway", "gene")) %>%
  # add column specifying how many additional genes must be selected
  left_join(number_of_additional_genes, by="pathway") %>%
  arrange(pathway, p.value) %>%
  group_by(pathway) %>%
  mutate(index = row_number()) %>%
  ungroup() %>%
  filter(index <= n) %>%
  select(gene, pathway, weight, p.value) %>%
  # merge with temporary mouse progeny matrix
  bind_rows(tmp_mouse_progeny) %>%
  select(gene, pathway, weight) %>%
  spread(pathway, weight, fill=0) %>%
  data.frame(row.names=1, check.names=F, stringsAsFactors = F)

write.csv(mouse_progeny, 
          "data/progeny_benchmark/models/progeny_matrix_mouse_v1.csv")
write_csv(full_mouse_matrix, 
          "data/progeny_benchmark/models/progeny_matrix_mouse_full_v1.csv")




x %>% count(pathway, weight) %>% filter(n == 6)
x %>% filter(pathway == "TNFa") %>% filter(round(weight,2) == 1.14) # problem

translated_matrix2 %>%
  select(gene, pathway, weight) %>%
  spread(pathway, weight, fill=0) %>%
  data.frame(check.names = F, stringsAsFactors = F) %>%
  write_csv("data/progeny_benchmark/models/progeny_matrix_mouse_v3.csv")
```

### Translate human DoRothEA regulon to mouse
```{r "translate human dorothea regulon to mice"}
# load annotation file and remove predicted mgi genes
annotation_mgi_hgnc = read_csv("data/annotations/annotation_mgi_hgnc.csv") %>%
  drop_na() %>%
  filter(!str_detect(mgi_symbol, "^Gm[:digit:]+"))
  

# load human regulon
dorothea_regulon_human_v1 = read_csv(
  "data/dorothea_benchmark/regulons/dorothea_regulon_human_v1.csv"
  )

# translate to mgi symbol
dorothea_regulon_mouse_v1 = dorothea_regulon_human_v1 %>%
  # first translate tfs
  rename(hgnc_symbol = tf) %>%
  inner_join(annotation_mgi_hgnc, by="hgnc_symbol") %>%
  select(tf = mgi_symbol, confidence, target, mor, likelihood) %>%
  # now translate targets
  rename(hgnc_symbol = target) %>%
  inner_join(annotation_mgi_hgnc, by="hgnc_symbol") %>%
  distinct(tf, confidence, target = mgi_symbol, mor, likelihood) %>%
  group_by(tf) %>%
  # due to the mapping it can happen that a single TF has several confidence
  # levels. To be more conservative the lowest level/max letter is chosen
  filter(confidence == max(confidence)) %>%
  ungroup() %>%
  select(tf, confidence, target, mor, likelihood)

write_csv(dorothea_regulon_mouse_v1,
          "data/dorothea_benchmark/regulons/dorothea_regulon_mouse_v1.csv")
```
